/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react/no-children-prop */
import Head from 'next/head';
import {
  Input, InputGroup, InputLeftElement, Button,
} from '@chakra-ui/react';
import { Search2Icon } from '@chakra-ui/icons';
import { useEffect } from 'react';
import styles from '../styles/Home.module.css';
import CharacterCard from '../components/CharacterCard';
import { getCharacterByLimit, getSeriesByCharacterId } from '../utils/apiCreator';

export default function Home() {
  useEffect(async () => {
    const res = await fetch(getCharacterByLimit(1));
    const data = await res.json();
    console.log(data);
    console.log(getSeriesByCharacterId(1011334));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Marvel Wikipedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.SearchAndResultContainer}>
        <div className={styles.ResultCountContainer}>
          Found 10000 characters
        </div>
        <div className={styles.SearchContainer}>
          <InputGroup>
            <InputLeftElement
              pointerEvents="none"
              children={<Search2Icon color="gray.300" />}
            />
            <Input type="text" placeholder="Search for any character" />
          </InputGroup>
          <Button colorScheme="teal" variant="outline">
            Search
          </Button>
        </div>
      </div>

      <div className={styles.CharactersList}>
        <CharacterCard />
      </div>

    </div>
  );
}
